export const SITE = {
  name: 'Lasky Metal Construction',
  legalName: 'Lasky Metal Construction LLC',
  tagline: 'Metal buildings built to last. Commercial, agricultural, and residential steel construction in Oklahoma and Arkansas.',
  phone: '(479) 000-0000',
  phoneHref: 'tel:+14790000000',
  email: 'joseglezrosas@gmail.com',
  address: {
    city: 'Siloam Springs',
    state: 'AR',
    zip: '72761',
  },
  geo: {
    lat: 36.1881,
    lng: -94.5405,
  },
  founded: 2021,
  hours: 'Mon-Fri 7a-5p, Sat by appointment',
  socials: {
    facebook: 'https://www.facebook.com/LaskyMetalConstruction',
  },
  url: 'https://laskymetalconstruction.com',
  ownerName: 'Jose Gonzalez Rosas',
  ownerTitle: 'Owner & Founder',
  serviceAreas: [
    'Siloam Springs',
    'Fayetteville',
    'Springdale',
    'Rogers',
    'Bentonville',
    'Fort Smith',
    'Tulsa',
    'Muskogee',
    'Tahlequah',
    'Claremore',
    'Broken Arrow',
    'Joplin',
  ],
} as const;
